--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);

--
-- Name: body_style; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.body_style AS ENUM (
    'sedan',
    'suv',
    'hatchback',
    'single_cab',
    'double_cab',
    'minivan',
    'van',
    'truck'
);


--
-- Name: fuel; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.fuel AS ENUM (
    'petrol',
    'diesel',
    'hybrid',
    'electric'
);


--
-- Name: status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status AS ENUM (
    'pending',
    'verified',
    'rejected',
    'conflict'
);


--
-- Name: transmission; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transmission AS ENUM (
    'manual',
    'automatic',
    'cvt'
);


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'super_admin',
    'garage_admin',
    'diagnostician',
    'insurance',
    'user'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    id text NOT NULL,
    "accountId" text NOT NULL,
    "providerId" text NOT NULL,
    "userId" text NOT NULL,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" timestamp without time zone,
    "refreshTokenExpiresAt" timestamp without time zone,
    scope text,
    password text,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL
);


--
-- Name: nhtsa_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nhtsa_models (
    id integer NOT NULL,
    make character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: nhtsa_models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nhtsa_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nhtsa_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session (
    id text NOT NULL,
    "expiresAt" timestamp without time zone NOT NULL,
    token text NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "ipAddress" text,
    "userAgent" text,
    "userId" text NOT NULL,
    "impersonatedBy" text
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    "emailVerified" boolean NOT NULL,
    image text,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    role public.user_role DEFAULT 'user'::public.user_role NOT NULL,
    banned boolean,
    "banReason" text,
    "banExpires" timestamp without time zone
);


--
-- Name: vds_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vds_cache (
    wmi character varying(3) NOT NULL,
    vds_code character varying(5) NOT NULL,
    spec_id integer NOT NULL,
    status public.status DEFAULT 'pending'::public.status NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: vehicle_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_ledger (
    id text NOT NULL,
    vin character varying(17) NOT NULL,
    manufacturer text NOT NULL,
    year text NOT NULL,
    model text NOT NULL,
    wmi text,
    vds text,
    vis text,
    plant text,
    country text,
    hardware_specs jsonb NOT NULL,
    "scannedBy" text NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    image_url text,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: vehicle_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_specs (
    id integer NOT NULL,
    hardware_specs jsonb NOT NULL
);


--
-- Name: vehicle_specs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicle_specs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.vehicle_specs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    "expiresAt" timestamp without time zone NOT NULL,
    "createdAt" timestamp without time zone,
    "updatedAt" timestamp without time zone
);


--
-- Name: verification_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_log (
    id integer NOT NULL,
    wmi character varying(3) NOT NULL,
    vds_code character varying(5) NOT NULL,
    proposed_spec_id integer NOT NULL,
    admin_id text NOT NULL,
    "timestamp" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: verification_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.verification_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wmi_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wmi_mapping (
    wmi character varying(3) NOT NULL,
    manufacturer character varying(100) DEFAULT 'Unknown'::character varying NOT NULL,
    country character varying(100),
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: nhtsa_models nhtsa_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhtsa_models
    ADD CONSTRAINT nhtsa_models_pkey PRIMARY KEY (id);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- Name: session session_token_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_token_unique UNIQUE (token);


--
-- Name: user user_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_unique UNIQUE (email);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: vds_cache vds_cache_wmi_vds_code_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vds_cache
    ADD CONSTRAINT vds_cache_wmi_vds_code_pk PRIMARY KEY (wmi, vds_code);


--
-- Name: vehicle_ledger vehicle_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_ledger
    ADD CONSTRAINT vehicle_ledger_pkey PRIMARY KEY (id);


--
-- Name: vehicle_ledger vehicle_ledger_vin_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_ledger
    ADD CONSTRAINT vehicle_ledger_vin_unique UNIQUE (vin);


--
-- Name: vehicle_specs vehicle_specs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_specs
    ADD CONSTRAINT vehicle_specs_pkey PRIMARY KEY (id);


--
-- Name: verification_log verification_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_log
    ADD CONSTRAINT verification_log_pkey PRIMARY KEY (id);


--
-- Name: verification verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_pkey PRIMARY KEY (id);


--
-- Name: wmi_mapping wmi_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wmi_mapping
    ADD CONSTRAINT wmi_mapping_pkey PRIMARY KEY (wmi);


--
-- Name: nhtsa_make_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nhtsa_make_idx ON public.nhtsa_models USING btree (make);


--
-- Name: account account_userId_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES public."user"(id);


--
-- Name: session session_userId_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES public."user"(id);


--
-- Name: vds_cache vds_cache_spec_id_vehicle_specs_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vds_cache
    ADD CONSTRAINT vds_cache_spec_id_vehicle_specs_id_fk FOREIGN KEY (spec_id) REFERENCES public.vehicle_specs(id);


--
-- Name: vds_cache vds_cache_wmi_wmi_mapping_wmi_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vds_cache
    ADD CONSTRAINT vds_cache_wmi_wmi_mapping_wmi_fk FOREIGN KEY (wmi) REFERENCES public.wmi_mapping(wmi);


--
-- Name: vehicle_ledger vehicle_ledger_scannedBy_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_ledger
    ADD CONSTRAINT "vehicle_ledger_scannedBy_user_id_fk" FOREIGN KEY ("scannedBy") REFERENCES public."user"(id);


--
-- Name: verification_log verification_log_admin_id_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_log
    ADD CONSTRAINT verification_log_admin_id_user_id_fk FOREIGN KEY (admin_id) REFERENCES public."user"(id);


--
-- Name: verification_log verification_log_proposed_spec_id_vehicle_specs_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_log
    ADD CONSTRAINT verification_log_proposed_spec_id_vehicle_specs_id_fk FOREIGN KEY (proposed_spec_id) REFERENCES public.vehicle_specs(id);


--
-- Name: verification_log verification_log_wmi_vds_code_vds_cache_wmi_vds_code_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_log
    ADD CONSTRAINT verification_log_wmi_vds_code_vds_cache_wmi_vds_code_fk FOREIGN KEY (wmi, vds_code) REFERENCES public.vds_cache(wmi, vds_code);


--
-- PostgreSQL database dump complete
--


